service: DEV-TLogExternal-v1

provider:
  name: aws
  runtime: python3.7
  lambdaHashingVersion: 20201221
  region: ap-south-1
  # profile: personalCaesarAcc
  timeout: 10 # You set a timeout of 10 seconds for the functions
  #role: arn:aws:iam::627768693377:role/serverlessLabs # Enter your Arn role here
  memorySize: 512

functions:
  first_function:
    handler: handler.first_function
    events:
      - http:
          path: /first
          method: get
  Second_function:
    handler: handler.second_function
    events:
      - http:
          path: /store
          method: post
